# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/
# CF_BRANCH value is auto set when pipeline is triggered
# Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/

version: 1.0
stages:
- github_clone
- build
- test
steps:
  github_clone:
    git: github
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    title: Cloning repository
    type: git-clone
  build:
    stage: build
    buildkit: true
    disable_push: true
    dockerfile: Dockerfile
    image_name: ${{CF_REPO_NAME}}/application
    tag: ${{CF_SHORT_REVISION}}
    title: Create Ruby Image
    type: build
    working_directory: ${{github_clone}}
  test:
    stage: test
    title: Running test
    working_directory: ${{github_clone}}
    image: ${{build}} # Use image ID of build step
    commands:
      - bundle exec rake test
